### ISSUE TITLE
duplicate names of custom fields for same group result in failure on upgrade to civicrm 4.3

### ISSUE THREAD

**Issue by thetechnaddict** [rajeshrhino/uk.co.nfpservices.module.civigiftaid#1]
There are two custom fields belonging to the Gift Aid Declaration group with the name 'Eligible_for_gift_aid'.

The first of these has the label matching the name, the second has the label 'UK Tax Payer?'

4.3 introduces a change a unique index on the custom_fields table consisting of the name and group_id - hence the upgrade fails.

What are the implications of renaming the second field to reflect its label?

**Comment by rajeshrhino** [comment]
Not able to replicate the issue.

## Steps followed
1. Installed CiviCRM 4.2.9
2. Installed CiviCRM GiftAid Extension for 4.2
3. Created few contributions records and added it to GiftAid batch
4. Upgraded to CiviCRM 4.3.1

Upgrade was successful without any problems.

After upgrade, when you use the GiftAid extension features, it will throw some fatal errors, as there are some changes in the core in class/file paths, etc. This will be fixed in CiviCRM GiftAid Extension for 4.3.
